In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2],[3,4]])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])

In [3]:
print(escalar)

5.679


In [4]:
# escalar.shape
# no tiene dimensión

In [5]:
print(vector)
vector.shape

[1 2 3]


(3,)

In [6]:
len(vector)

3

In [8]:
print(matriz)
matriz.shape

[[1 2]
 [3 4]]


(2, 2)

In [9]:
len(matriz)
#Nos devuelve la cantidad de objetos en la primera columna

2

In [10]:
print(matriz.size)
#Nos devuelve la multimlicacion de dimensiones

4


In [12]:
print(tensor.shape)

(3, 3, 3)


In [13]:
print(tensor.size)

27


# Transposicion y Suma - matrices escalares

In [14]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]]
])

In [16]:
#escalar_t = escalar.T
#No tiene transpuesta al no tener dimensiones

In [18]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [19]:
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [21]:
print(matriz.shape)

(3, 2)


In [22]:
print(matriz_t.shape)

(2, 3)


In [23]:
tensor_t =tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [24]:
print(tensor)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


In [25]:
matriz_t_t = matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B

print('A = ',A)
print("")
print('B = ',B)
print("")
print('c = ',C)

A =  [[1 2]
 [3 4]
 [5 6]]

B =  [[6 5]
 [4 3]
 [2 1]]

c =  [[7 7]
 [7 7]
 [7 7]]


In [31]:
D = matriz + escalar
print(D)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]


## Suma de Matrices y Vectores (broadcasting)

In [32]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [34]:
#A = vector + matriz
#Bota error por no tener la misma dimension

In [37]:
A = matriz.T + vector
print(A)
#Broadcasting: Extender la dimension de menor tamaño hasta completar o igualar la de mayor tamaño

[[ 4  7 10]
 [ 5  8 11]]


In [38]:
C = matriz + 42
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [40]:
D = matriz + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]


# Producto entre una matriz y un vector

In [41]:
escalar = 5.769
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [48]:
#Broadcasting
A = matriz * vector
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [49]:
#Producto interno: regresa un escalar
B = matriz.dot(vector)
print(B)

[ 8 18 28]


In [47]:
C = np.dot(matriz, vector)
print(C)

[ 8 18 28]


## Producto interno entre 2 matrices

In [50]:
A = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])

In [51]:
print(A.shape)

(4, 3)


In [52]:
print(B.shape)

(3, 2)


In [55]:
C = A.dot(B)
print(C)

[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]


In [56]:
#D = B.dot(A)
#Bota error porque la dimesion de la fila B no es igual a la dimension de la columna de A